### ISSUE TITLE
Parsed content is still escaped

### ISSUE THREAD

**Issue by Morgul** [almost/safe-html#1]
Once you parse a string, such as `'<p>I <3 you</p>'`,  the output (assume `p` tags are not allowed) is:

`''I &lt;3 you`.

I would expect:

`I <3 you`

**Comment by almost** [comment]
This is the correct behaviour. The library is producing sanitised HTML, that is to say HTML in a canonical form with only a restricted set of tags and attributes allowed. It sounds like you maybe want an HTML to text converter?
